# Generated by Django 6.1.1 on 2026-09-12 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstn', models.CharField(max_length=50)),
                ('lastn', models.CharField(max_length=50)),
                ('birth_d', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pages', models.IntegerField()),
                ('price', models.IntegerField()),
                ('desc', models.TextField()),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.autor')),
            ],
        ),
    ]
